### ISSUE TITLE
Master please give me answer

### ISSUE THREAD

**Issue by nghiakuke** [github150620/a9g_tracker#1]
Module Sim A9G have future GMS and GPS. When give code project sms into pudding A9G work ok, when give code GPS into pudding A9G work ok but when i have a project have SMS and GPS into pudding A9G work not ok . Please show me a project full functional of A9G about SMS and GPS

Thank a lot lot lot...
If have details contact to me by mail  tanhannghia@gmail.com

**Comment by nghiakuke** [comment]
Where are masters?

**Comment by github150620** [comment]
I am sorry. I have never used the SMS in A9G.

**Comment by nghiakuke** [comment]
do you have good project? please give me learn more

**Comment by github150620** [comment]
https://docs.ai-thinker.com/gprs
I hope it can help you.
